/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package site.hadef.database3.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Gender service. Represents a row in the &quot;gender&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>site.hadef.database3.model.impl.GenderModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>site.hadef.database3.model.impl.GenderImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Gender
 * @generated
 */
@ProviderType
public interface GenderModel extends BaseModel<Gender> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gender model instance should use the {@link Gender} interface instead.
	 */

	/**
	 * Returns the primary key of this gender.
	 *
	 * @return the primary key of this gender
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gender.
	 *
	 * @param primaryKey the primary key of this gender
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the gender ID of this gender.
	 *
	 * @return the gender ID of this gender
	 */
	public long getGenderId();

	/**
	 * Sets the gender ID of this gender.
	 *
	 * @param genderId the gender ID of this gender
	 */
	public void setGenderId(long genderId);

	/**
	 * Returns the gender name of this gender.
	 *
	 * @return the gender name of this gender
	 */
	@AutoEscape
	public String getGenderName();

	/**
	 * Sets the gender name of this gender.
	 *
	 * @param genderName the gender name of this gender
	 */
	public void setGenderName(String genderName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(site.hadef.database3.model.Gender gender);

	@Override
	public int hashCode();

	@Override
	public CacheModel<site.hadef.database3.model.Gender> toCacheModel();

	@Override
	public site.hadef.database3.model.Gender toEscapedModel();

	@Override
	public site.hadef.database3.model.Gender toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}